services:
  - type: web
    name: pricepulse
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m py_compile app.py && gunicorn app:app --bind 0.0.0.0:$PORT
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
