services:
  - type: web
    name: pricepulse
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -m py_compile app.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.12
